service: whale-alerts-bot

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  bundle:
    linting: false
    excludeFiles: "**/*.test.ts"
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  timeout: 15
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  app:
    handler: src/handler.handler
    environment:
      QUEUE_URL: ${construct:purchases.queueUrl}
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'

constructs:
    purchases:
        type: queue
        fifo: true
        worker:
            handler: src/worker.handler
        extensions:
            queue:
                Properties:
                    MaximumMessageSize: 262144

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline
  - serverless-lift
